### ISSUE TITLE
App setup

### ISSUE THREAD

**Issue by juliemahlke** [juliemahlke/capstone-project#1]
## Description
Set up app structure

## Tasks
- [x] create React-App
- [x] delete unneeded files
- [x] connect Git repository
- [x] Styled Components
- [x] .prettierrc
- [x] install npm
- [x] .gitignore
- [x] package.json
- [x] Font awesome
- [x] Google Font
- [x] global Styles 

## Size
Mi
