### ISSUE TITLE
Trip-detailpage

### ISSUE THREAD

**Issue by juliemahlke** [juliemahlke/capstone-project#12]
## Value statement
As a **user who likes to travel**
I need a page for any trip 
so that **I can add notes** for ideas, sightseeing, hotel-links for example.

## Description
<img src="https://user-images.githubusercontent.com/59579694/76293993-5d76f800-62b2-11ea-9d3a-6fb941b0857a.jpg" width="200" />

## Acceptance criteria
- [x] the new page is found at the path "/trip/{tripId}"
- [x] click on list-item opens the detailpage
- [x] the new page includes the default-image at the top, the title, the date and a link to create a new note (preparing)
- [x] there is a button to go back to the list

## Tasks
- [x]  Create new page
- [x]  Implement onclick to list-item
- [x]  include uid for better ids
- [x]  Implement list-item-id to page-routing
- [x]  Implement backlink to list
- [x]  Styling

## Size
L
