### ISSUE TITLE
Notelist (trip-detailpage)

### ISSUE THREAD

**Issue by juliemahlke** [juliemahlke/capstone-project#19]
## Value statement
As a **user who likes to travel**
I need a page for any trip 
so that **I can add notes** for ideas, sightseeing, hotel-links for example.

## Description
<img src="https://user-images.githubusercontent.com/59579694/76350007-4a444680-630b-11ea-9965-7d051439f119.jpg" width="200" />

## Acceptance criteria
- [x] a clearly arranged notelist
- [x] items-preview shows the title and the note with 3 lines, the rest of lines are invisible
- [x] a click of note-item shows the total view

## Tasks
- [x]  Create new components Note and NoteList in storybook
- [x]  include a static list of 3-4 notes to detailpage
- [x]  Implement onclick to note-item, onclick shows the total view
- [x]  Include Note and Notelist to storybook
- [x]  Styling

## Size
L
