### ISSUE TITLE
Trip-List

### ISSUE THREAD

**Issue by juliemahlke** [juliemahlke/capstone-project#2]
## Value statement
As a **user who likes to travel**
I need a list of all trips to organize it

## Description
<table>
<td><img src="https://user-images.githubusercontent.com/59579694/75625215-39356000-5bbc-11ea-8db2-ba4d1b23e332.jpeg" width="200" /></td>
<td><img src ="https://user-images.githubusercontent.com/59579694/75633611-96ee9a00-5c06-11ea-8b0c-95f4125d0cc3.jpg" width="200" />
</td>
</table>

A trip contains:
- Title
- Date / vacationtime (e.g. 05.06. - 10.06.20)
- Titleimage (default)

## Acceptance criteria
- [x] The list is clear and concise
- [x] A trip contains an image on the left side 
- [x] Title and date are simple text and among each other on the right side

## Tasks
- [x] Component TripList 
- [x] Component TripListItem 
- [x] Styling
- [ ] UX-test with normal/long/short textlength
- [x] UX-test with long Item-List (Scroll behaviour?)

## Size
M

**Comment by felixufer** [comment]
Add list title to acceptance criteria?
