### ISSUE TITLE
Create trips

### ISSUE THREAD

**Issue by juliemahlke** [juliemahlke/capstone-project#3]
## Value statement
As a **user who likes to travel**
I need to add a new trip for travel-wishes or/and planned trips. 

## Description
<table>
<td>
<img src="https://user-images.githubusercontent.com/59579694/75625232-6124c380-5bbc-11ea-9151-4be00a9b3b0d.jpeg" width="200" /></td>

<td>
<img src="https://user-images.githubusercontent.com/59579694/75633705-91458400-5c07-11ea-9535-fbfca42600ff.jpg" width="200" />
</td>
</table>

- A form with 2 text-inputs for title + date
- A button to submit [Trip erstellen]

## Acceptance criteria
- [x] Click to +, the form is opening
- [x] The form is found at the path "/create"
- [x] The button is disabled until input for title is filled
- [x] There is a button to cancel creation of new trip
- [x] The first input has focus at start and after submit
- [x] The form is cleared after submit
- [x] The user ends up in list after submit
- [x] The new card is added at the top

## Tasks
- [x] Include add-button on Triplist
- [x] Component CreateTrip
- [x] Add routing
- [x] Form-element
- [x] State: trip, setTrip
- [x] Styling
- [x] Usability Test on mobile and desktop

## Size
L

**Comment by felixufer** [comment]
How to cancel creation of new trip?
