### ISSUE TITLE
Save trips (locally)

### ISSUE THREAD

**Issue by juliemahlke** [juliemahlke/capstone-project#4]
## Value statement
As a **user who likes to travel**
I need to **keep my trips through sessions**
so that **I don't loose my valuable**

## Description
- no visible impact

## Acceptance criteria
- [ ] every change on the state <code>trips</code> should trigger a save to localStorage
- [ ] Reload of the page should load trips from localStorage

## Tasks
- [ ]  Create services for localStorage
- [ ]  Implement save/load for <code>trips</code>
- [ ]  UX-test on desktop and mobile

## Size
M
