### ISSUE TITLE
Delete trips

### ISSUE THREAD

**Issue by juliemahlke** [juliemahlke/capstone-project#5]
## Value statement
As a **user who likes to travel**
I keep my trips through sessions and 
**I need to delete trips**
For example if a trip is cancelled

## Description
- no visible impact

## Acceptance criteria
- [x] Click on each trip should delete that trip

## Tasks
- [x]  Implement delete for <code>trips</code>
- [x]  UX-test on desktop and mobile

## Size
M
